### ISSUE TITLE
В файлах  tireout*.dat неполный заголовок

### ISSUE THREAD

**Issue by gvlipunova** [pabolmasov/HACol#30]
В заголовке не описана какая-то одна из колонок

пример:
     tireout00010.dat                                                                                                                                           Row 1    Col 1   
# t = 0.00038038028005168745s
# format: r/rstar -- rho -- v -- u/umag
1.0 930508.2306765724 -0.00024315370660712884 0.1934978318364287 0.952764822146296

**Comment by pabolmasov** [comment]
да, спасибо! Добавил, это локальный поток, qloss
