### ISSUE TITLE
Extra Space at the beginning of line in output ASCII files

### ISSUE THREAD

**Issue by gvlipunova** [pabolmasov/HACol#36]
https://github.com/pabolmasov/HACol/blob/2bcffea1df0abf7ed11c7f3a339ebb6847e81ae1/tire_MPI.py#L1382
Please remove a space after "\n" at the referred line and at the  next line of the code. Currently, there is something like  fflux.write("AAAAA\n ") which produces a space at the beginnign of a next line in output fflux and  leads to errors by some plotting subroutines.

**Comment by pabolmasov** [comment]
corrected
